### ISSUE TITLE
Tutorial test does not work. Missing files in the module

### ISSUE THREAD

**Issue by JeevaTM** [bjascob/pySimpleNLG#1]
I installed the simplenlg module locally and ran your tutorial test file. Got this error.

>  Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license()" for more information.
> >>> 
> ================ RESTART: C:\Users\jb00557372\Desktop\test.py ================
> EEEEEEEEEEEE
> ======================================================================
> ERROR: testSection10 (__main__.TutorialTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\Users\jb00557372\Desktop\test.py", line 234, in testSection10
>     lexicon = Lexicon.getDefaultLexicon()      # default simplenlg lexicon
>   File "C:\Users\jb00557372\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simplenlg\lexicon\Lexicon.py", line 33, in getDefaultLexicon
>     return XMLLexicon()
>   File "C:\Users\jb00557372\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simplenlg\lexicon\XMLLexicon.py", line 46, in __init__
>     self.createLexicon(lexicon_fn)
>   File "C:\Users\jb00557372\AppData\Local\Programs\Python\Python37-32\lib\site-packages\simplenlg\lexicon\XMLLexicon.py", line 52, in createLexicon
>     tree = ET.parse(xmlfile)
>   File "C:\Users\jb00557372\AppData\Local\Programs\Python\Python37-32\lib\xml\etree\ElementTree.py", line 1197, in parse
>     tree.parse(source, parser)
>   File "C:\Users\jb00557372\AppData\Local\Programs\Python\Python37-32\lib\xml\etree\ElementTree.py", line 587, in parse
>     source = open(source, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jb00557372\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\simplenlg\\resources\\default-lexicon.xml'

**Comment by bjascob** [comment]
It can't find the file `default-lexicon.xml` which is in `simplenlg/resources/`.  You'll need that file to use the project.  It's for more that just the tests.  

The code knows where to load the file from because in `simplenlg/__init__.py` there's a line at the top that says... `resource_directory = os.path.join(os.path.dirname(__file__), 'resources')`   This tells the loader that it's in the resource directory, one level down from the `__init__`.  In Linux, pip installs that data file in the correct location.  You can do a temporary fix by copying that file to the location of the error it's giving you (`C:\Users\.....\simplenlg\resources\default-lexicon.xml`) or setting the correct permission on it if that's the issue.  If all else fails, you could hard-code the path into `resource_directory = xx` in the `__init__.py` file.

What command did you use to install?  Let me know what you find as a fix and maybe I can make an update to the installer.

The code should work under Windows but I didn't make `runAllUnitTests.py`  Windows friendly.  When I look at that script there's a few places where I use "/" path separators instead of "\\".  You'll probably need to change those.  If that script gives you issues you can always run each test individually by simply executing each test file.  The script in the main directory is just for convenience.

**Comment by bjascob** [comment]
Using `pip install simplenlg` on my Windows 10 machine installs the `default-lexicon.xml` file correctly in the `...\Python37\Lib\site-packages\simplenlg\resources` directory.

I made a small change to the `runAllUnitTests.py` to fix paths and an `import importlib` issue.  Now it runs all the tests correctly and they pass for me in Windows.

**Comment by JeevaTM** [comment]
Thank you.
